# Generated by Django 2.2.12 on 2020-09-03 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vender', '0001_initial'),
        ('Myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoginModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField(default=1234)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField()),
                ('status', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.TextField()),
                ('items', models.ManyToManyField(to='Vender.FoodItemsModel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRegistrationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField(unique=True)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=20)),
                ('OTP', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myadmin.CityModel')),
            ],
        ),
    ]
